### ISSUE TITLE
.exe not needed...and breaks sample_admb

### ISSUE THREAD

**Issue by jimianelli** [Cole-Monnahan-NOAA/adnuts#16]
ff <- file.path(path, paste0(model, ".exe"))

windoze doesn't need to have this extension (I don't think) and it breaks models in bsd/linux so why have it...

**Comment by colemonnahan** [comment]
@jimianelli @John-R-Wallace 

>90% of my emails about issues are people having the wrong path/model name so I need some sort of informative check in there. What is the extension on the file for Mac/Linux? I don't have access to those OS's so it's really hard to test outside of Windows.

**Comment by colemonnahan** [comment]
I just had the idea to see what R2admb does and here is what they do:

https://github.com/bbolker/R2admb/blob/396c8d5a88d7a42503ed76829ae950a498b163c2/R2admb/R/base_funs.r#L97

So I tried that in this commit:
https://github.com/colemonnahan/adnuts/commit/345108ec180b41c8aa4d2ff4b18d71321965cdaa

Could you two please test it on your non-win systems? @jimianelli @John-R-Wallace

**Comment by John-R-Wallace** [comment]
For Linux (version below), commit 345108e 
<https://github.com/colemonnahan/adnuts/commit/345108ec180b41c8aa4d2ff4b18d71321965cdaa>:

system.time(pilot <- sample_admb("./ss", iter=iter, thin=thin, 
seeds=seeds, init=inits, parallel=FALSE, chains=reps, warmup=warmup, 
path=m, cores=reps, algorithm='RWM'))

works fine now.


FYI, just 'ss' only gives the usage:

system.time(pilot <- sample_admb("ss", iter=iter, thin=thin, 
seeds=seeds, init=inits, parallel=FALSE, chains=reps, warmup=warmup, 
path=m, cores=reps, algorithm='RWM'))
ss: "n" is invalid family
Usage: ss [ OPTIONS ]
        ss [ OPTIONS ] [ FILTER ]
    -h, --help          this message
    -V, --version       output version information
    -n, --numeric       don't resolve service names
    -r, --resolve       resolve host names
...


-John

P.S.  Good idea looking to see what R2admb does.

----------------------- Linux version 
---------------------------------------

NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
