### ISSUE TITLE
Deprecated sample_tmb

### ISSUE THREAD

**Issue by Maschette** [Cole-Monnahan-NOAA/adnuts#17]
Hi just noticed that sample_tmb is now not exported and the file is called sample_tmb_deprecated.r just wondering if there is an alternate place for accessing this now? 
If so it may be worth adding a deprecated message using `.deprecated` for it telling people where to look. 

Cheers

**Comment by Cole-Monnahan-NOAA** [comment]
Hi @Maschette I didn't realize anyone was using it. How do you use this function? 

You can always access it like `adnuts:::sample_tmb` as temporary fix, or I can re-export it if you really want it. In general I think people should move to using `tmbstan` as it is much faster. I mention this in the vignette but you're right I didn't use a `.depcreate` statement. `sample_tmb` is no longer under development, is not tested nor maintained.

**Comment by Maschette** [comment]
It is a new use for me. I am in a fisheries TMB course with Andre Punt and he uses it in his example models. 

The confusing thing for me was that whilst it is not exported the sample_tmb.rd documentation files are still there which means you can find it using `?sample_tmb` but then you go to use it and it is not exported.

**Comment by Cole-Monnahan-NOAA** [comment]
@Maschette Please install and use the dev branch. I got `sample_tmb` working again so you can use it short-term. I did have a `.Deprecate` statement in there. If it doesn't work please reopen this issue with more details.

**Comment by Maschette** [comment]
@Cole-Monnahan-NOAA just testing out the dev branch and it both appears to run and give the deprecated message: 

```
mcmcout <- sample_tmb(obj=model,seeds=1:3,init=list(list(model$env$last.par.best)), iter=2000,chains=1,algorithm="NUTS")

Starting NUTS at 2020-08-14 11:23:43
Chain 1, Iteration:    1/2000 [  0%] (Warmup)

Chain 1, Iteration: 2000/2000 [100%] (Sampling)
Final acceptance ratio=0.78, and target=0.8
Final step size=0.884; after 1000 warmup iterations
 Elapsed Time: 0.9 seconds (Warmup)
 Elapsed Time: 0.5 seconds (Sampling)
 Elapsed Time: 1.4 seconds (Total)
Warning message:
Use tmbstan::tmbstan instead, sample_tmb is deprecated and no longer under development/maintenance 

```

It does however seem to return an invalid object for extract_samples():
```
>   post2 <- extract_samples(mcmcout)
Error in extract_samples(mcmcout) : fit is not a valid object
```

The same code from the CRAN Version works fine. 

My guess is that https://github.com/Cole-Monnahan-NOAA/adnuts/blob/2191245dc6a83aac19f0b13e4f33d36f57f18c48/R/sample_tmb_deprecated.R#L208
needs to become `return(invisible(adfit(result)))`

**Comment by Cole-Monnahan-NOAA** [comment]
You're correct that was the mistake. I also added back the monitor and checked that results from `tmb_sample` work with `plot` and `pairs_admb`. Please let me know if there are other simple features you find missing. Thanks for pointing these out and apologies for forgetting it.
