### ISSUE TITLE
Model name inconsistencies with MacOS

### ISSUE THREAD

**Issue by Cole-Monnahan-NOAA** [Cole-Monnahan-NOAA/adnuts#21]
The user needs to use model='./model' instead of just model='model' when using a MacOS. I handled this for the MCMC part but it was not done consistently through with the checks and other aspects. Ideally the user specifies just "model" and the "/." part is added internally. This makes code OS-agnostic and cleaner on the user end.

I tried to fix this in a new branch and would like some help testing it (I don't have access to a MacOS machine). @wStockhausen would you please try this? Or maybe @jimianelli? 

`devtools::install_github('Cole-Monnahan-NOAA/adnuts', ref='fix_path')`

Then test this with code like

`fit <- sample_rwm(model=m, path=p, iter=100, chains=1)`

Where the variables m and p vary. Basically try to break it. It should gracefully and informatively error out when either is wrong. Also what happens if you pass e.g., m='./simple' and it gets added on again internally? That works on Windows.

**Comment by k-doering-NOAA** [comment]
@Cole-Monnahan-NOAA in case it is helpful, there is some code in this run_SS_models function in r4ss that deals with different oses: https://github.com/r4ss/r4ss/blob/development/R/run_SS_models.R . It sounds like you already have a solution, but thought I would mention in case you run into issues and need some more ideas for dealing with making os agnostic code.

Another idea for testing on mac and linux when you don't have local access to either is setting up a github actions job using one of the github linux or mac runners - there are unlimited min for open source repos, so run time isn't an issue. I recently made this one in r4ss that runs some testthat tests that require the SS executable (the tests are skipped when the exe isn't available): https://github.com/r4ss/r4ss/blob/development/.github/workflows/run-tests-with-SS.yml .

 It isn't perfect (a few R packages created problems that required a workaround for the r4ss job), but setting up a github action job would give you another way to test on other OSes and keep testing as code is changed.

**Comment by Cole-Monnahan-NOAA** [comment]
Fixed and merged into dev branch so closing this issue.
