### ISSUE TITLE
Update to NOAA themed pkgdown site

### ISSUE THREAD

**Issue by haleyoleynik** [Cole-Monnahan-NOAA/adnuts#30]
We've reorganized the Fisheries Integrated Toolbox GitHub Organization, and by doing so the `.css` file that makes your pkgdown site NOAA colors has been changed. 

To update your pkgdown site, edit your `extra.css` to `@import url("https://nmfs-fish-tools.github.io/nmfspalette/extra.css");`

[Here's an example from r4MAS.](https://github.com/nmfs-fish-tools/r4MAS/blob/master/pkgdown/extra.css)

**Comment by Cole-Monnahan-NOAA** [comment]
Fixed in [this commit](https://github.com/Cole-Monnahan-NOAA/adnuts/commit/c5931f553145c092cdf797b989dac739f76dae09). Thanks!
