### ISSUE TITLE
Add a variable to help for sample_nuts

### ISSUE THREAD

**Issue by jimianelli** [Cole-Monnahan-NOAA/adnuts#31]
Consider changing the line in the examples for sample from:

`init <- function() rnorm(2)`

to

`init <- function() rnorm(numpars)`

where numpars would be set based on the problem.

This is so that in case someone misses that the example is a 2-parameter regression, it would be more extensible. Also `init=` not really defined elsewhere (at least with clear instructions for alternatives from `NULL`.

**Comment by Cole-Monnahan-NOAA** [comment]
[Updated](https://github.com/Cole-Monnahan-NOAA/adnuts/commit/ff480043f0544611e5bf78000c844e5ca681ca30). The help file was incomplete and out of date. So I updated that, so e.g. `?sample_nuts` has this:

> Can be either a list containing a vector for each chain, a function which returns a vector of parameters, or NULL which specifies to use the MLE as stored in the admodel.hes file. It is generally recommended to use dispersed initial values to improve diagnostic checks (starting from the same point makes it less likely to find multiple modes).

Thanks for reporting it. Closing it for now but open to updated dox for `init`.
