### ISSUE TITLE
Search for par file is too broad

### ISSUE THREAD

**Issue by okenk** [Cole-Monnahan-NOAA/adnuts#32]
The function `.read_mle_fit` searches for a par file using the line
`ff <- list.files()[grep(x = list.files(), pattern = ".par")]`

This does not actually search for files containing ".par" because of how R does regular expressions. Instead, it returns all files containing "par," including, say "plot_comparisons.png." 

If you change the `pattern` argument from `.par` to `\\.par` it will actually search for ".par".

**Comment by Cole-Monnahan-NOAA** [comment]
This was actually fixed last year on the dev branch in this [commit](https://github.com/Cole-Monnahan-NOAA/adnuts/commit/49345214422a7d3360fad79c3a7ffa30abad1bae). So if it's an immediate problem install that branch. Otherwise it'll get fixed on the next release. Thanks!
