### ISSUE TITLE
Duplicated entry in help for adapt_delta

### ISSUE THREAD

**Issue by iagomosqueira** [Cole-Monnahan-NOAA/adnuts#33]
There are two entries for the `adapt_delta` element of the control object

- <https://github.com/Cole-Monnahan-NOAA/adnuts/blob/main/R/sample_admb.R#L104>
- <https://github.com/Cole-Monnahan-NOAA/adnuts/blob/main/R/sample_admb.R#L108>

which imply a difference in usage and class. Which one is correct?

**Comment by Cole-Monnahan-NOAA** [comment]
The former is correct. I fixed the documentation in [this commit](https://github.com/Cole-Monnahan-NOAA/adnuts/commit/bca6e651bc3c7f77485f2b9a87c95bb4f08ff1e6). Thanks for pointing it out.
